/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cld;

import javax.swing.ImageIcon;

/**
 *
 * @author Victor1
 */
public class green extends javax.swing.JFrame {

    String mostrar = "";
    String sign;
    /**
     * Creates new form green
     */
    public green() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(480, 720);
        this.setTitle("Calcololatrice");
        ImageIcon img = new ImageIcon("images/icono.png");
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        n9 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        equal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 255, 215));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        n9.setBackground(new java.awt.Color(246, 252, 246));
        n9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 42)); // NOI18N
        n9.setForeground(new java.awt.Color(51, 78, 50));
        n9.setText("9");
        n9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 78, 50), 3, true));
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        jPanel1.add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 90, 90));

        n0.setBackground(new java.awt.Color(246, 252, 246));
        n0.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 42)); // NOI18N
        n0.setForeground(new java.awt.Color(51, 78, 50));
        n0.setText("0");
        n0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 78, 50), 3, true));
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        jPanel1.add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 90, 90));

        equal.setBackground(new java.awt.Color(246, 252, 246));
        equal.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 42)); // NOI18N
        equal.setForeground(new java.awt.Color(51, 78, 50));
        equal.setText("=");
        equal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 78, 50), 3, true));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
//        show.setText(show.getText() + "9");
    }//GEN-LAST:event_n9ActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
//        show.setText(show.getText() + "0");
    }//GEN-LAST:event_n0ActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
//        String showText = show.getText(), extract = "";
//        String numOne = "", numTwo = "";
//        boolean pass = false;
//        // Separating numbers and sign
//        for (int i = 0; i < showText.length(); i++) {
//            // Number 1
//            extract = showText.substring(i, i + 1);
//            // Here takes the number 1 until pass gets true and can get the sign and the number 2
//            if (pass == false) {
//                // Type of operation
//                if ("+".equals(extract) || "-".equals(extract) || "*".equals(extract) || "/".equals(extract)) {
//                    sign = extract;
//                    pass = true;
//                } else { // Number One
//                    numOne = numOne + extract;
//                }
//            } else { // Number Two
//                numTwo = numTwo + extract;
//            }
//        }
//        int nOne = Integer.parseInt(numOne);
//        int nTwo = Integer.parseInt(numTwo);
//        System.out.println("Signo: " + sign);
//        System.out.println("Numero 1: " + numOne);
//        System.out.println("Numero 2: " + numTwo);
        
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(green.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(green.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(green.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(green.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new green().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton n0;
    private javax.swing.JButton n9;
    // End of variables declaration//GEN-END:variables
}
